Ft verification mail #165020201
andela/ah-kgl-avengers-backend pull request #13
Opened 2019-04-11 13:54 UTC by niyobobo

## What does this PR do?
Sending an email to the users upon successful registration (After creating their account).
## Description of Task to be completed?
- Integration of nodemailer as mailing service.
- Connecting nodemailer with sendGrid as SMTP transporter 
## How should this be manually tested?
- Clone the repo and checkout to ft-verification-mail-#165020201
- `npm install && npm start`
- Import { sentActivationMail } module in a certain file  from config directory. 
- use function with this parameter object `{ name, body, url, email, subject }`
- run in the terminal `node <classname>.js`.
## Any background context you want to provide?
This feature requires an internet connection to work.
## What are the relevant pivotal tracker stories?
[#165020201](https://www.pivotaltracker.com/n/projects/2321840)
## Questions:
- Travis is not directly supporting  FTP and SMTP. (direct test is not working on TravisCI we have to mock the response)

2019-04-11 14:08 UTC, shemaeric reviewed
Good Job, You can look at feedback to make the codes well.

2019-04-11 14:08 UTC, shemaeric commented on .eslintrc
>  	"root": true,
@niyobobo , For the sake of the pretty codes, it would be better to work on the indentation in the file.

2019-04-11 14:08 UTC, shemaeric commented on tests/mailer.test.js
> +  it('Send activation email', async () => {
@niyobobo It would be better if the test description was too descriptive.

2019-04-11 23:11 UTC, avpaul submitted a review, later dismissed
Looks good to me!

2019-04-12 12:31 UTC, fridolinho reviewed
Add an empty line at the end of each file

2019-04-12 12:31 UTC, fridolinho commented on config/verificationMail.js
> +      return error;
I suggest returning customized error

2019-04-15 07:49 UTC, aaronsekisambu requested changes
please fix the old comments

2019-04-15 09:35 UTC, niyobobo commented on config/verificationMail.js
> +      return error;
I solved this.

2019-04-15 09:37 UTC, avpaul submitted a review, later dismissed
Looks good to me

2019-04-15 09:47 UTC, fridolinho approved these changes
Great work done.

2019-04-15 09:48 UTC, fridolinho submitted a review, later dismissed

2019-04-15 11:24 UTC, aaronsekisambu submitted a review, later dismissed

2019-04-15 22:03 UTC, avpaul requested changes
Looks good to me except the .eslint

2019-04-15 22:03 UTC, avpaul commented on .eslintrc
> +>>>>>>> [Feature #165020201] Add activation route
@niyobobo It's like you forgot to resolve conflicts in this file while rebasing or merging? I think that you should keep the incoming changes only.

2019-04-16 05:26 UTC, niyobobo commented on .eslintrc
> +>>>>>>> [Feature #165020201] Add activation route
Uuuuuuuhhhhhhh how come can I push such an error like this😎. Let me work on it.

2019-04-16 06:08 UTC, niyobobo commented on .eslintrc
> +>>>>>>> [Feature #165020201] Add activation route
Solved now.

2019-04-16 06:34 UTC, merged

2019-04-16 06:35 UTC, avpaul approved these changes