#165020220 Social sharing
andela/ah-kgl-avengers-backend pull request #27
Opened 2019-05-02 08:06 UTC by fridolinho

## What does this PR do?
Add social sharing
## Description of Task to be completed?
- Validate if shared article exists
- Share using email, facebook and twitter
## How should this be manually tested?
1. Run these commands
     - clone https://github.com/andela/ah-kgl-avengers-backend.git
     - git checkout ft-social-sharing-165020220
     - npm install
     - npm test
2. 
     - send a get request on  localhost:3000/api/v1/articles/:slug/facebook-share
                                             localhost:3000/api/v1/articles/:slug/twitter-share
                                             localhost:3000/api/v1/articles/:slug/email-share
         slug is an article unique identifier, get it from existing article.
## Any background context you want to provide?

## What are the relevant pivotal tracker stories?
[#165020220 Social sharing](https://www.pivotaltracker.com/story/show/165020220)
## Screenshots (if appropriate)
N/A
## Questions:
N/A

2019-05-02 09:51 UTC, aaronsekisambu requested changes

2019-05-02 09:51 UTC, aaronsekisambu commented on controllers/articles.js
> +      message: 'facebook share',
@fridolinho I think the message here is not descriptive. Could you please work on it.

2019-05-02 09:51 UTC, aaronsekisambu commented on controllers/articles.js
> +      message: 'twitter share'
@fridolinho same applies to this one. It's also not descriptive.

2019-05-02 09:51 UTC, aaronsekisambu commented on controllers/articles.js
> +      message: 'email share',
@fridolinho and this one.

2019-05-02 10:02 UTC, niyobobo submitted a review, later dismissed
Better if you return a descriptive message rather than `facebook share, twitter share,......`

2019-05-02 16:06 UTC, fridolinho commented
Resolved everything

2019-05-02 16:07 UTC, aaronsekisambu submitted a review, later dismissed

2019-05-03 06:55 UTC, shemaeric submitted a review, later dismissed
LGTM

2019-05-03 13:32 UTC, daud1 approved these changes
👍

2019-05-03 13:32 UTC, merged