#165020227 commenting on any text in article
andela/ah-kgl-avengers-backend pull request #28
Opened 2019-05-07 22:15 UTC by shemaeric

## What does this PR do?

## Description of Task to be completed?

## How should this be manually tested?

## Any background context you want to provide?

## What are the relevant pivotal tracker stories?

## Screenshots (if appropriate)

## Questions:

2019-05-08 10:36 UTC, aaronsekisambu requested changes
LGTM

2019-05-08 10:36 UTC, aaronsekisambu commented on routes/api/articles.js
> +  '/articles/:slug/text-comment',
@shemaeric This is just an observation that requires clarification. Should we stick to camelCase convention or this "text-comment"? Like the one, you have used here.

2019-05-08 10:36 UTC, aaronsekisambu commented on routes/api/articles.js
> +  '/articles/:slug/text-comment',
@shemaeric here

2019-05-08 11:07 UTC, shemaeric commented on routes/api/articles.js
> +  '/articles/:slug/text-comment',
Thank you @aaronsekisambu as this is the part of url string not a keyword, I find it better using "text-comment" than comelCase in URL

2019-05-08 13:12 UTC, avpaul requested changes

2019-05-08 13:12 UTC, avpaul commented on controllers/commentText.js
> +        const commentOnText = await Comments.findOrCreate({
@shemaeric The request body contents `i.e: text, startIndex, endIndex, body` are not validated. When they are not given the query fails this throws an error. The response has a **500 status code** and a message that the server is unable to process the request. It would be better if you validate the content and send a custom error when they are not sent in the request body.

2019-05-08 13:12 UTC, avpaul commented on controllers/commentText.js
> +        return res.status(201).send({
@shemaeric The response from the findOrCreate query behaves differently according to whether it created the entry or found it as shown in the pictures: 
The first one used **create** as the comment was not there
<img width="683" alt="Screen Shot 2019-05-08 at 14 13 37" src="https://user-images.githubusercontent.com/24508902/57374737-e22d4d00-719b-11e9-8fea-8a7fc7a183c3.png">
The second one used **find** because the same comment was there
<img width="581" alt="Screen Shot 2019-05-08 at 14 13 47" src="https://user-images.githubusercontent.com/24508902/57374775-f8d3a400-719b-11e9-8375-291e4a4cf56b.png">

You should check it the data on the two images, one has an ID which is needed when we want to like a comment but the other does not. It would be better if the response has consistent data.

2019-05-08 13:12 UTC, avpaul commented on controllers/commentText.js
> +    } = req.body;
@shemaeric check comments made on line 45

2019-05-08 13:12 UTC, avpaul commented on controllers/commentText.js
> +          where: { id: commentId, author: user.id },
@shemaeric When a user different than the comment author tries to update the comment, the response is a 500/internal server error.  I think you should customize it to a 401/unauthorized.

2019-05-08 13:12 UTC, avpaul commented on controllers/commentText.js
> +  static async getHighlighted(req, res) {
@shemaeric I get well the function of this method `getHighlighted` from the comments you say that It should get all highlighted text on an article. The response is an array with this object:
```javascript
{
    "highlitedText": "Lorem",
    "User": {
            "username": "tester1",
            "image": null
    }
},
```

When the comment has no highlighted text the response has `"highlitedText": null`. I think you should go through the response and only return comments with highlighted text. Plus, you should add the index of the highlighted text.

2019-05-08 13:14 UTC, avpaul commented on routes/api/articles.js
> +  '/articles/:slug/text-comment',
I also think we should avoid camel case in URLs.

2019-05-08 13:21 UTC, avpaul requested changes

2019-05-08 13:21 UTC, avpaul commented on controllers/commentText.js
> +        res.status(404).send({
@shemaeric Here you should **return** the response, i.e: it should be `return res.status(404).send...`

2019-05-08 13:23 UTC, avpaul commented on controllers/commentText.js
> +        res.status(404).send({
@shemaeric Even on line 36 in the same file, there is no **return**.

2019-05-08 15:15 UTC, shemaeric commented on controllers/commentText.js
> +        res.status(404).send({
Thank you @avpaul

2019-05-08 15:15 UTC, shemaeric commented on controllers/commentText.js
> +          where: { id: commentId, author: user.id },
Thank you

2019-05-08 15:16 UTC, shemaeric commented on controllers/commentText.js
> +        return res.status(201).send({
Thank you for the feedback @avpaul

2019-05-08 19:03 UTC, aaronsekisambu submitted a review, later dismissed

2019-05-08 21:15 UTC, avpaul submitted a review, later dismissed

2019-05-09 09:03 UTC, fridolinho reviewed
Your codes look good anyway.

2019-05-09 09:03 UTC, fridolinho commented on controllers/commentText.js
> +        const commentOnText = await Comments.findOrCreate({
That's a great, (findOrCreate) was new for me. thank you for this

2019-05-09 09:03 UTC, fridolinho commented on tests/highlights.test.js
> +});
you need to abide eslint rules and add an empty line at the end

2019-05-09 09:08 UTC, fridolinho submitted a review, later dismissed
LGTM

2019-05-09 09:55 UTC, niyobobo submitted a review, later dismissed
Thank you for great work and working on feedback from team members.

LGTM

2019-05-09 14:46 UTC, niyobobo approved these changes

2019-05-09 14:52 UTC, fridolinho approved these changes

2019-05-09 14:53 UTC, avpaul approved these changes
LGTM

2019-05-09 15:11 UTC, merged