#165020195- Setup tests
andela/ah-kgl-avengers-backend pull request #4
Opened 2019-04-03 22:31 UTC by shemaeric

## What does this PR do?
This PR set up the tests to ensure that the back end has all functionality working as intended. 
## Description of Task to be completed?
- Install mocha as the testing framework, chai, and chai-http. 
- create the basic tests for the index file of the root endpoint
## How should this be manually tested?
clone this repo ``` https://github.com/andela/ah-kgl-avengers-backend ```
cd into the project,
 checkout into ``` ch-setup-tests-165020195 ``` 
run ``` npm run test ```
## Any background context you want to provide?
N/A
## What are the relevant pivotal tracker stories?
[165020195](https://www.pivotaltracker.com/n/projects/2321840)
## Screenshots (if appropriate)
N/A
## Questions:
N/A

2019-04-04 08:46 UTC, avpaul commented on tests/index.test.js
> +    it('should pass as the response is json object and with message', (done) => {
I would be better if you express the `it` block in terms of expected return as shown below:
```javascript
     it('returns a response with status code 200 and JSON object', (done) => {...});
```

2019-04-04 09:40 UTC, daud1 commented
Please fix your resolve all merge conflicts so I can merge this in.

2019-04-04 09:47 UTC, daud1 requested changes
Please take a look at the comments and make the requested changes.

2019-04-04 09:47 UTC, daud1 commented on index.js
> -const fs = require("fs"),
Some of the code removed from this file is actually useful.
Please review and ensure that you have not removed any essential code.
Feel free to reach out for guidance.

2019-04-08 07:26 UTC, daud1 requested changes
Please implement all changes requested.

2019-04-08 07:26 UTC, daud1 commented on .github/pull_request_template.md
> +    Postman
Please remove this from the PR Template.

2019-04-08 07:37 UTC, daud1 commented on tests/index.test.js
> +>>>>>>> 8567040330a7a51363f03ca668b8ef43b1c30ca9
These markings are left in with merge conflicts.
This usually means that you didn't resolve all merge conflicts.
Please look into this.

2019-04-08 07:55 UTC, daud1 approved these changes

2019-04-08 07:57 UTC, merged